import { z } from "zod";

/**
 * Chrome extensions hub — data contract.
 *
 * `src/content/extensions.json` is generated by Tabmill; this schema is the
 * contract it targets (documented in README.md § Extensions data contract).
 * The JSON is a top-level array of entries.
 */

// Static routes under /extensions that a slug must not shadow.
const RESERVED_SLUGS = ["support"];

export const extensionSchema = z.object({
  /** URL segment: /extensions/<slug>. Kebab-case. */
  slug: z
    .string()
    .regex(/^[a-z0-9-]+$/, "slug must be kebab-case")
    .refine((s) => !RESERVED_SLUGS.includes(s), "slug is reserved"),
  name: z.string(),
  /** One line, shown on the directory card and the detail page. */
  pitch: z.string(),
  /**
   * Chrome Web Store listing. Omit (or null) while the extension isn't in the
   * store yet — pages then show "In development" instead of an install button.
   */
  store_url: z.string().url().nullish(),
  /** Full tool page on the portfolio site — the page that carries the SEO copy. */
  tool_page_url: z.string().url(),
  /** Every permission in the manifest, each with a plain-language reason. */
  permissions: z.array(z.object({ name: z.string(), reason: z.string() })).default([]),
  /**
   * What leaves the user's browser, one description per item. Empty means
   * nothing is collected — the privacy page then states all processing is local.
   */
  data_collected: z.array(z.string()).default([]),
  /** Whether the extension sends usage analytics. */
  analytics: z.boolean().default(false),
  /** Releases; any order in the file, rendered newest first. */
  changelog: z
    .array(
      z.object({
        version: z.string(),
        date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
        notes: z.string(),
      }),
    )
    .default([]),
  /** draft = hidden from /extensions and 404 at its URLs. */
  status: z.enum(["draft", "published"]).default("draft"),
});
export type Extension = z.infer<typeof extensionSchema>;

const files = import.meta.glob("../content/extensions.json", { eager: true, import: "default" });

function loadAll(): Extension[] {
  const raw = Object.values(files)[0];
  if (!Array.isArray(raw)) {
    if (raw !== undefined) console.error("[extensions] extensions.json must be an array");
    return [];
  }
  const entries: Extension[] = [];
  raw.forEach((item, i) => {
    const parsed = extensionSchema.safeParse(item);
    if (!parsed.success) {
      // Fail loud in dev/build logs, but don't crash the site for one bad entry.
      console.error(`[extensions] invalid entry #${i}:`, parsed.error.flatten());
      return;
    }
    if (JSON.stringify(parsed.data).includes("FILL")) {
      console.warn(`[extensions] "${parsed.data.slug}" still has ‹FILL› placeholders`);
    }
    entries.push({
      ...parsed.data,
      changelog: [...parsed.data.changelog].sort((a, b) => (a.date < b.date ? 1 : -1)),
    });
  });
  return entries.sort((a, b) => a.name.localeCompare(b.name));
}

const ALL = loadAll();

export function getAllExtensions(): Extension[] {
  return ALL.filter((e) => e.status === "published");
}

export function getExtensionBySlug(slug: string): Extension | undefined {
  return getAllExtensions().find((e) => e.slug === slug);
}

/** Last-updated date for the privacy page: newest release, if any. */
export function privacyUpdated(ext: Extension): string | undefined {
  return ext.changelog[0]?.date;
}
