/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebSystemsRouteImport } from './routes/web-systems'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContentRouteImport } from './routes/content'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkIndexRouteImport } from './routes/work/index'
import { Route as NotesIndexRouteImport } from './routes/notes/index'
import { Route as AitoolsIndexRouteImport } from './routes/aitools/index'
import { Route as WorkSlugRouteImport } from './routes/work/$slug'
import { Route as NotesYoctoVsBuildrootRouteImport } from './routes/notes/yocto-vs-buildroot'
import { Route as AitoolsTextGeneratorRouteImport } from './routes/aitools/text-generator'
import { Route as AitoolsImageAnalyzerRouteImport } from './routes/aitools/image-analyzer'

const WebSystemsRoute = WebSystemsRouteImport.update({
  id: '/web-systems',
  path: '/web-systems',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AitoolsIndexRoute = AitoolsIndexRouteImport.update({
  id: '/aitools/',
  path: '/aitools/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesYoctoVsBuildrootRoute = NotesYoctoVsBuildrootRouteImport.update({
  id: '/notes/yocto-vs-buildroot',
  path: '/notes/yocto-vs-buildroot',
  getParentRoute: () => rootRouteImport,
} as any)
const AitoolsTextGeneratorRoute = AitoolsTextGeneratorRouteImport.update({
  id: '/aitools/text-generator',
  path: '/aitools/text-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const AitoolsImageAnalyzerRoute = AitoolsImageAnalyzerRouteImport.update({
  id: '/aitools/image-analyzer',
  path: '/aitools/image-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/content': typeof ContentRoute
  '/services': typeof ServicesRoute
  '/web-systems': typeof WebSystemsRoute
  '/aitools/image-analyzer': typeof AitoolsImageAnalyzerRoute
  '/aitools/text-generator': typeof AitoolsTextGeneratorRoute
  '/notes/yocto-vs-buildroot': typeof NotesYoctoVsBuildrootRoute
  '/work/$slug': typeof WorkSlugRoute
  '/aitools/': typeof AitoolsIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/content': typeof ContentRoute
  '/services': typeof ServicesRoute
  '/web-systems': typeof WebSystemsRoute
  '/aitools/image-analyzer': typeof AitoolsImageAnalyzerRoute
  '/aitools/text-generator': typeof AitoolsTextGeneratorRoute
  '/notes/yocto-vs-buildroot': typeof NotesYoctoVsBuildrootRoute
  '/work/$slug': typeof WorkSlugRoute
  '/aitools': typeof AitoolsIndexRoute
  '/notes': typeof NotesIndexRoute
  '/work': typeof WorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/content': typeof ContentRoute
  '/services': typeof ServicesRoute
  '/web-systems': typeof WebSystemsRoute
  '/aitools/image-analyzer': typeof AitoolsImageAnalyzerRoute
  '/aitools/text-generator': typeof AitoolsTextGeneratorRoute
  '/notes/yocto-vs-buildroot': typeof NotesYoctoVsBuildrootRoute
  '/work/$slug': typeof WorkSlugRoute
  '/aitools/': typeof AitoolsIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/content'
    | '/services'
    | '/web-systems'
    | '/aitools/image-analyzer'
    | '/aitools/text-generator'
    | '/notes/yocto-vs-buildroot'
    | '/work/$slug'
    | '/aitools/'
    | '/notes/'
    | '/work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/content'
    | '/services'
    | '/web-systems'
    | '/aitools/image-analyzer'
    | '/aitools/text-generator'
    | '/notes/yocto-vs-buildroot'
    | '/work/$slug'
    | '/aitools'
    | '/notes'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/content'
    | '/services'
    | '/web-systems'
    | '/aitools/image-analyzer'
    | '/aitools/text-generator'
    | '/notes/yocto-vs-buildroot'
    | '/work/$slug'
    | '/aitools/'
    | '/notes/'
    | '/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  ContentRoute: typeof ContentRoute
  ServicesRoute: typeof ServicesRoute
  WebSystemsRoute: typeof WebSystemsRoute
  AitoolsImageAnalyzerRoute: typeof AitoolsImageAnalyzerRoute
  AitoolsTextGeneratorRoute: typeof AitoolsTextGeneratorRoute
  NotesYoctoVsBuildrootRoute: typeof NotesYoctoVsBuildrootRoute
  WorkSlugRoute: typeof WorkSlugRoute
  AitoolsIndexRoute: typeof AitoolsIndexRoute
  NotesIndexRoute: typeof NotesIndexRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/web-systems': {
      id: '/web-systems'
      path: '/web-systems'
      fullPath: '/web-systems'
      preLoaderRoute: typeof WebSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aitools/': {
      id: '/aitools/'
      path: '/aitools'
      fullPath: '/aitools/'
      preLoaderRoute: typeof AitoolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/yocto-vs-buildroot': {
      id: '/notes/yocto-vs-buildroot'
      path: '/notes/yocto-vs-buildroot'
      fullPath: '/notes/yocto-vs-buildroot'
      preLoaderRoute: typeof NotesYoctoVsBuildrootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aitools/text-generator': {
      id: '/aitools/text-generator'
      path: '/aitools/text-generator'
      fullPath: '/aitools/text-generator'
      preLoaderRoute: typeof AitoolsTextGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aitools/image-analyzer': {
      id: '/aitools/image-analyzer'
      path: '/aitools/image-analyzer'
      fullPath: '/aitools/image-analyzer'
      preLoaderRoute: typeof AitoolsImageAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  ContentRoute: ContentRoute,
  ServicesRoute: ServicesRoute,
  WebSystemsRoute: WebSystemsRoute,
  AitoolsImageAnalyzerRoute: AitoolsImageAnalyzerRoute,
  AitoolsTextGeneratorRoute: AitoolsTextGeneratorRoute,
  NotesYoctoVsBuildrootRoute: NotesYoctoVsBuildrootRoute,
  WorkSlugRoute: WorkSlugRoute,
  AitoolsIndexRoute: AitoolsIndexRoute,
  NotesIndexRoute: NotesIndexRoute,
  WorkIndexRoute: WorkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
